/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.controller;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import model.data_warga;
import model.jumlah_warga;
import model.kartu_keluarga;

/**
 *
 * @author Yosua
 */
public class data_warga_view extends javax.swing.JFrame {
        controller controller;
        String nik;
    /**
     * Creates new form data_warga_view
     */
    public data_warga_view() throws SQLException {
        initComponents();
        this.controller = new controller();
        this.nik = new String();
        this.showComboBoxKK();
        this.showComboBoxStatus();
        this.showComboBoxJenisKelamin();
        this.showTableKK();
        this.showTableWarga();
     
    }
    
    public void showComboBoxKK() throws SQLException{
        DefaultComboBoxModel dtmKK = new DefaultComboBoxModel();
        for(kartu_keluarga kk : this.controller.getKartu_Keluarga()){
            dtmKK.addElement(kk.getNo_kk());
        }
        this.cbKK.setModel(dtmKK);
    }
    public void showComboBoxStatus(){
        this.cbStatusKel.removeAllItems();
        this.cbStatusKel.addItem("Bapak");
        this.cbStatusKel.addItem("Ibu");
        this.cbStatusKel.addItem("Anak");
    }
    
    public void showComboBoxJenisKelamin(){
        this.cbJenisKelamin.removeAllItems();
        this.cbJenisKelamin.addItem("Pria");
        this.cbJenisKelamin.addItem("Wanita");
    }
    
    public void showTableKK() throws SQLException{
        DefaultTableModel dtmKK = new DefaultTableModel(new String[]{"NO KK", "KOTA", "ALAMAT", "JUMLAH ORANG"},0);
        dtmKK.setRowCount(0);
        for(jumlah_warga jw : this.controller.getJumlah_warga()){
            dtmKK.addRow(new String[]{jw.getNO_KK(), jw.getKota(), jw.getAlamat(), jw.getJumlah()});
        }
        this.tblKK.setModel(dtmKK);
    }
    
    public void showTableWarga() throws SQLException{
        DefaultTableModel dtmwarga = new DefaultTableModel(new String[]{"NO_KK", "NIK", "NAMA", "STATUS KELUARGA"},0);
        dtmwarga.setRowCount(0);
        for(data_warga dw : this.controller.getDataWarga()){
            dtmwarga.addRow(new String[]{dw.getNo_kk(), dw.getNik().toString(), dw.getNama(), dw.getStatus_keluarga()});
        }
        this.tblwarga.setModel(dtmwarga);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbKK = new javax.swing.JComboBox<>();
        cbStatusKel = new javax.swing.JComboBox<>();
        cbJenisKelamin = new javax.swing.JComboBox<>();
        tfTanggalLahir = new javax.swing.JTextField();
        tfUmur = new javax.swing.JTextField();
        tfNoTelp = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKK = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDetail = new javax.swing.JTextArea();
        btnTambah = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblwarga = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnSet = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfNik = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NO KARTU KELUARGA");

        jLabel3.setText("NAMA");

        jLabel4.setText("STATUS KELUARGA");

        jLabel5.setText("TANGGAL LAHIR");

        jLabel6.setText("JENIS KELAMIN");

        jLabel7.setText("UMUR");

        jLabel8.setText("NO TELP");

        cbKK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbStatusKel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tfUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUmurActionPerformed(evt);
            }
        });

        tblKK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKK);

        taDetail.setColumns(20);
        taDetail.setRows(5);
        jScrollPane2.setViewportView(taDetail);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        tblwarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblwarga);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSet.setText("Set");
        btnSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel2.setText("NIK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cbJenisKelamin, javax.swing.GroupLayout.Alignment.TRAILING, 0, 141, Short.MAX_VALUE)
                                                .addComponent(tfUmur, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(tfNoTelp, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSet)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUpdate)
                                        .addGap(41, 41, 41)
                                        .addComponent(btnTambah)))
                                .addComponent(cbStatusKel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(46, 46, 46)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfNama)
                                        .addComponent(cbKK, 0, 141, Short.MAX_VALUE)
                                        .addComponent(tfNik))))
                            .addGap(73, 73, 73))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(149, 149, 149)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(tfNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(cbKK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbStatusKel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(tfNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnSet)
                            .addComponent(btnUpdate))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnView)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUmurActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        try{
            String select = this.tblKK.getValueAt(this.tblKK.getSelectedRow(), 0).toString();
            kartu_keluarga kk = this.controller.getDetail_Keluarga(select);
            
            String text = ""
                + "NO KARTU KELUARGA : " + kk.getNo_kk() + "\n"
                    + "KODE POS : " + kk.getKode_pos() + "\n"
                    + "PROVINSI : " + kk.getProvinsi() + "\n"
                    + "KOTA : " + kk.getKota() + "\n"
                    + "ALAMAT : " + kk.getAlamat() + "\n"
                    + "\nJUMLAH ORANG : " + kk.getArrdata_warga().get(0).getJumlah();
            if(kk.getArrdata_warga().get(0).getJumlah().equals("0")){
                text += "\n------------------------------------------------------";
            }else{
                ArrayList<data_warga> dw = kk.getArrdata_warga();
            for(int i = 0;i < dw.size();++i){
            text += "\n"
                    + "NIK : " + dw.get(i).getNik().toString() + "\n"
                    + "NAMA : " + dw.get(i).getNama() + "\n"
                    + "STATUS KELUARGA : " + dw.get(i).getStatus_keluarga() + "\n"
                    + "TANGGAL LAHIR : " + new SimpleDateFormat("dd/MM/yyyy").format(dw.get(i).getTanggal_lahir()) + "\n"
                    + "JENIS KELAMIN : " + dw.get(i).getJenis_kelamin() + "\n"
                    + "UMUR : " + dw.get(i).getUmur().toString() + "\n"
                    + "NO TELP : " + dw.get(i).getNo_telp() + "\n";
            }
            }
            this.taDetail.setText(text);
            
        }catch (SQLException ex) {
                Logger.getLogger(data_warga_view.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
            try {
                data_warga data = new data_warga();
                data.setNik(Integer.parseInt(this.tfNik.getText()));
                data.setNo_kk(this.cbKK.getSelectedItem().toString());
                data.setNama(this.tfNama.getText());
                data.setStatus_keluarga(this.cbStatusKel.getSelectedItem().toString());
                data.setTanggal_lahir(new SimpleDateFormat("dd/MM/yyyy").parse(this.tfTanggalLahir.getText()));
                data.setJenis_kelamin(this.cbJenisKelamin.getSelectedItem().toString());
                data.setUmur(Integer.parseInt(this.tfUmur.getText()));
                data.setNo_telp(tfNoTelp.getText());
                
                this.controller.insert_warga(data);
                this.showTableKK();
                this.showTableWarga();
                tfNama.setText("");
                tfNoTelp.setText("");
                tfTanggalLahir.setText("");
                tfUmur.setText("");
            } catch (ParseException ex) {
                Logger.getLogger(data_warga_view.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(data_warga_view.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
            try {
                String select = tblwarga.getValueAt(tblwarga.getSelectedRow(), 1).toString();
                this.controller.delete_warga(select);
                this.showTableKK();
                this.showTableWarga();
            } catch (SQLException ex) {
                Logger.getLogger(data_warga_view.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed
        try {
            data_warga data = this.controller.GetDataWargaNik(this.tblwarga.getValueAt(this.tblwarga.getSelectedRow(), 1).toString());
            this.tfNik.setText(data.getNik().toString());
            Integer coun = 0;
            for(kartu_keluarga dw : this.controller.getKartu_Keluarga()){
                if(!this.tblwarga.getValueAt(this.tblwarga.getSelectedRow(), 0).toString().equals(dw.getNo_kk())){
                    coun+=1;
                }else{
                    break;
                }
            }
            
            this.cbKK.setSelectedIndex(coun);
            this.tfNama.setText(data.getNama());
            if(data.getStatus_keluarga().equals("Bapak")){
                coun = 0;
            }
            else if (data.getStatus_keluarga().equals("Ibu")){
                coun = 1;
            }
            else{
                coun = 2;
            }
            this.cbStatusKel.setSelectedIndex(coun);
            String tgl = new SimpleDateFormat("dd/MM/yyyy").format(data.getTanggal_lahir());
            this.tfTanggalLahir.setText(tgl);
            if(data.getJenis_kelamin().equals("Pria")){
                coun = 0;
            }
            else{
                coun = 1;
            }
            this.cbJenisKelamin.setSelectedIndex(coun);
            this.tfUmur.setText(data.getUmur().toString());
            this.tfNoTelp.setText(data.getNo_telp());
            this.nik = this.tblwarga.getValueAt(this.tblwarga.getSelectedRow(), 1).toString();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSetActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
            try {
                data_warga dw = new data_warga();
                dw.setNik(Integer.parseInt(this.tfNik.getText()));
                dw.setNo_kk(this.cbKK.getSelectedItem().toString());
                dw.setNama(this.tfNama.getText());
                dw.setStatus_keluarga(this.cbStatusKel.getSelectedItem().toString());
                dw.setTanggal_lahir(new Date(this.tfTanggalLahir.getText()));
                dw.setJenis_kelamin(this.cbJenisKelamin.getSelectedItem().toString());
                dw.setUmur(Integer.parseInt(this.tfUmur.getText()));
                dw.setNo_telp(this.tfNoTelp.getText());
                this.controller.UpdateWarga(dw, this.nik);
                this.showTableWarga();
            } catch (SQLException ex) {
                Logger.getLogger(data_warga_view.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_warga_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_warga_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_warga_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_warga_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new data_warga_view().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(data_warga_view.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSet;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cbJenisKelamin;
    private javax.swing.JComboBox<String> cbKK;
    private javax.swing.JComboBox<String> cbStatusKel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea taDetail;
    private javax.swing.JTable tblKK;
    private javax.swing.JTable tblwarga;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNik;
    private javax.swing.JTextField tfNoTelp;
    private javax.swing.JTextField tfTanggalLahir;
    private javax.swing.JTextField tfUmur;
    // End of variables declaration//GEN-END:variables
}
